/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _RPC_H_RPCGEN
#define _RPC_H_RPCGEN

#include <rpc/rpc.h>

#include <pthread.h>

#ifdef __cplusplus
extern "C" {
#endif


struct imprimir_strings_1_argument {
	char *nombre;
	char *op;
	char *file;
	char *fecha;
};
typedef struct imprimir_strings_1_argument imprimir_strings_1_argument;

#define IMPRIMIR_PROG 0x31234567
#define IMPRIMIR_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define IMPRIMIR_STRINGS 1
extern  enum clnt_stat imprimir_strings_1(char *, char *, char *, char *, void *, CLIENT *);
extern  bool_t imprimir_strings_1_svc(char *, char *, char *, char *, void *, struct svc_req *);
extern int imprimir_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define IMPRIMIR_STRINGS 1
extern  enum clnt_stat imprimir_strings_1();
extern  bool_t imprimir_strings_1_svc();
extern int imprimir_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_imprimir_strings_1_argument (XDR *, imprimir_strings_1_argument*);

#else /* K&R C */
extern bool_t xdr_imprimir_strings_1_argument ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_RPC_H_RPCGEN */
