/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "rpc.h"

bool_t
imprimir_strings_1_svc(char *nombre, char *op, char *file, char *fecha, void *result,  struct svc_req *rqstp)
{
	bool_t retval;
	retval = TRUE;

	if (file == "") {
		printf("%s		%s		%s\n", nombre, op, fecha);
	} else {
		printf("%s		%s %s		%s\n", nombre, op, file, fecha);
	}

	return retval;
}

int
imprimir_prog_1_freeresult (SVCXPRT *transp, xdrproc_t xdr_result, caddr_t result)
{
	xdr_free (xdr_result, result);

	/*
	 * Insert additional freeing code here, if needed
	 */

	return 1;
}
