/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "rpc.h"

bool_t
xdr_imprimir_strings_1_argument (XDR *xdrs, imprimir_strings_1_argument *objp)
{
	 if (!xdr_string (xdrs, &objp->nombre, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->op, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->file, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->fecha, ~0))
		 return FALSE;
	return TRUE;
}
