/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "rpc.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

enum clnt_stat 
imprimir_strings_1(char *nombre, char *op, char *file, char *fecha, void *clnt_res,  CLIENT *clnt)
{
	imprimir_strings_1_argument arg;
	arg.nombre = nombre;
	arg.op = op;
	arg.file = file;
	arg.fecha = fecha;
	return (clnt_call (clnt, IMPRIMIR_STRINGS, (xdrproc_t) xdr_imprimir_strings_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_void, (caddr_t) clnt_res,
		TIMEOUT));
}
