/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "tuplas.h"

bool_t
xdr_CoordAux (XDR *xdrs, CoordAux *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->x))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->y))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_VectorDoubles (XDR *xdrs, VectorDoubles *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_u_int (xdrs, &objp->V_value2_len))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->V_value2_val, 32,
		sizeof (double), (xdrproc_t) xdr_double))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_Peticion (XDR *xdrs, Peticion *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->key))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->value1, 256))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->N_value2))
		 return FALSE;
	 if (!xdr_VectorDoubles (xdrs, &objp->V_value2))
		 return FALSE;
	 if (!xdr_CoordAux (xdrs, &objp->value3))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_Respuesta (XDR *xdrs, Respuesta *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->result))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_RespuestaGetValue (XDR *xdrs, RespuestaGetValue *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->result))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->value1, 256))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->N_value2))
		 return FALSE;
	 if (!xdr_VectorDoubles (xdrs, &objp->V_value2))
		 return FALSE;
	 if (!xdr_CoordAux (xdrs, &objp->value3))
		 return FALSE;
	return TRUE;
}
