/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "tuplas.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

enum clnt_stat 
destroy_1_1(Respuesta *clnt_res, CLIENT *clnt)
{
	 return (clnt_call (clnt, destroy_1, (xdrproc_t) xdr_void, (caddr_t) NULL,
		(xdrproc_t) xdr_Respuesta, (caddr_t) clnt_res,
		TIMEOUT));

}

enum clnt_stat 
set_value_1_1(Peticion arg1, Respuesta *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, set_value_1,
		(xdrproc_t) xdr_Peticion, (caddr_t) &arg1,
		(xdrproc_t) xdr_Respuesta, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
get_value_1_1(Peticion arg1, RespuestaGetValue *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, get_value_1,
		(xdrproc_t) xdr_Peticion, (caddr_t) &arg1,
		(xdrproc_t) xdr_RespuestaGetValue, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
modify_value_1_1(Peticion arg1, Respuesta *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, modify_value_1,
		(xdrproc_t) xdr_Peticion, (caddr_t) &arg1,
		(xdrproc_t) xdr_Respuesta, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
delete_key_1_1(Peticion arg1, Respuesta *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, delete_key_1,
		(xdrproc_t) xdr_Peticion, (caddr_t) &arg1,
		(xdrproc_t) xdr_Respuesta, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
exist_1_1(Peticion arg1, Respuesta *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, exist_1,
		(xdrproc_t) xdr_Peticion, (caddr_t) &arg1,
		(xdrproc_t) xdr_Respuesta, (caddr_t) clnt_res,
		TIMEOUT));
}
