/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _TUPLAS_H_RPCGEN
#define _TUPLAS_H_RPCGEN

#include <rpc/rpc.h>

#include <pthread.h>

#ifdef __cplusplus
extern "C" {
#endif


struct CoordAux {
	int x;
	int y;
};
typedef struct CoordAux CoordAux;

struct VectorDoubles {
	u_int V_value2_len;
	double V_value2_val[32];
};
typedef struct VectorDoubles VectorDoubles;

struct Peticion {
	int key;
	char *value1;
	int N_value2;
	struct VectorDoubles V_value2;
	CoordAux value3;
};
typedef struct Peticion Peticion;

struct Respuesta {
	int result;
};
typedef struct Respuesta Respuesta;

struct RespuestaGetValue {
	int result;
	char *value1;
	int N_value2;
	struct VectorDoubles V_value2;
	CoordAux value3;
};
typedef struct RespuestaGetValue RespuestaGetValue;

#define TUPLAS_PROG 0x20000001
#define TUPLAS_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define destroy_1 1
extern  enum clnt_stat destroy_1_1(Respuesta *, CLIENT *);
extern  bool_t destroy_1_1_svc(Respuesta *, struct svc_req *);
#define set_value_1 2
extern  enum clnt_stat set_value_1_1(Peticion , Respuesta *, CLIENT *);
extern  bool_t set_value_1_1_svc(Peticion , Respuesta *, struct svc_req *);
#define get_value_1 3
extern  enum clnt_stat get_value_1_1(Peticion , RespuestaGetValue *, CLIENT *);
extern  bool_t get_value_1_1_svc(Peticion , RespuestaGetValue *, struct svc_req *);
#define modify_value_1 4
extern  enum clnt_stat modify_value_1_1(Peticion , Respuesta *, CLIENT *);
extern  bool_t modify_value_1_1_svc(Peticion , Respuesta *, struct svc_req *);
#define delete_key_1 5
extern  enum clnt_stat delete_key_1_1(Peticion , Respuesta *, CLIENT *);
extern  bool_t delete_key_1_1_svc(Peticion , Respuesta *, struct svc_req *);
#define exist_1 6
extern  enum clnt_stat exist_1_1(Peticion , Respuesta *, CLIENT *);
extern  bool_t exist_1_1_svc(Peticion , Respuesta *, struct svc_req *);
extern int tuplas_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define destroy_1 1
extern  enum clnt_stat destroy_1_1();
extern  bool_t destroy_1_1_svc();
#define set_value_1 2
extern  enum clnt_stat set_value_1_1();
extern  bool_t set_value_1_1_svc();
#define get_value_1 3
extern  enum clnt_stat get_value_1_1();
extern  bool_t get_value_1_1_svc();
#define modify_value_1 4
extern  enum clnt_stat modify_value_1_1();
extern  bool_t modify_value_1_1_svc();
#define delete_key_1 5
extern  enum clnt_stat delete_key_1_1();
extern  bool_t delete_key_1_1_svc();
#define exist_1 6
extern  enum clnt_stat exist_1_1();
extern  bool_t exist_1_1_svc();
extern int tuplas_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_CoordAux (XDR *, CoordAux*);
extern  bool_t xdr_VectorDoubles (XDR *, VectorDoubles*);
extern  bool_t xdr_Peticion (XDR *, Peticion*);
extern  bool_t xdr_Respuesta (XDR *, Respuesta*);
extern  bool_t xdr_RespuestaGetValue (XDR *, RespuestaGetValue*);

#else /* K&R C */
extern bool_t xdr_CoordAux ();
extern bool_t xdr_VectorDoubles ();
extern bool_t xdr_Peticion ();
extern bool_t xdr_Respuesta ();
extern bool_t xdr_RespuestaGetValue ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_TUPLAS_H_RPCGEN */
